import {
  Mail,
  User,
  GraduationCap,
  BriefcaseBusiness,
  MapPin,
} from "lucide-react";
import { FaLinkedinIn, FaGithub, FaWhatsapp } from "react-icons/fa";

import type {
  IInfo,
  IQualifications,
  ISkills,
  IInfoData,
} from "@/constants/about/interfaces";

export const info: IInfo = {
  Username: {
    title: "Sidarta Oliveira",
    description: "Software Engineer - Full Stack/GIS Developer",
    Icon: User,
  },
  GitHub: {
    title: "GitHub",
    description: "ssidartaa",
    portifolio: "https://github.com/ssidartaa/portfolio",
    link: "https://github.com/ssidartaa",
    Icon: FaGithub,
  },
  Email: {
    title: "Email",
    link: "mailto:ssidataaoli@gmail.com",
    description: "ssidataaoli@gmail.com",
    Icon: Mail,
  },
  Whatsapp: {
    title: "WhatsApp",
    link: "https://wa.me/5568992571066",
    description: "+55 (68) 99257-1066",
    Icon: FaWhatsapp,
  },
  LinkedIn: {
    title: "LinkedIn",
    link: "https://linkedin.com/in/ssidartaa",
    Icon: FaLinkedinIn,
  },
  Formation: {
    title: "Bachelor's Degree in Computer Science",
    description: "Estácio",
    Icon: GraduationCap,
  },
  Role: {
    title: "Software Engineer - Full Stack/GIS Developer",
    description: "Role",
    Icon: BriefcaseBusiness,
  },
  Location: {
    title: "Curitiba - Paraná, Brazil",
    link: "https://www.google.com/maps/search/?api=1&query=Curitiba+Parana+Brazil",
    Icon: MapPin,
  },
};

export const contactInfos: IInfoData[] = [
  info.Email,
  info.Whatsapp,
  info.GitHub,
  info.LinkedIn,
  info.Location,
];

export const qualifications: IQualifications[] = [
  {
    title: "education",
    data: [
      {
        school: "Kenzie Academy Brasil",
        qualification: "Full Stack Developer",
        years: "Mar 2022 - Mar 2023",
        location: "Cruzeiro do Sul - Acre, Brazil (Remote)",
      },
      {
        school: "Estácio",
        qualification: "Bachelor's Degree in Computer Science",
        years: "Jan 2023 - Today",
        location: "Curitiba - Paraná, Brazil (Remote)",
      },
    ],
  },
  {
    title: "experience",
    data: [
      {
        company: "SENOGRAFIA DESENVOLVIMENTO E SOLUÇÕES",
        role: "Frontend Junior Developer",
        years: "Jan 2025 - Today",
        location: "Curitiba - Paraná, Brazil (In-Person)",
        description: [
          "Leadership in the development of customized technological solutions for a diverse range of clients, including municipal governments, state entities, and private corporations.",
          "Implementation of innovative tools focused on web development and geospatial applications, ensuring robust and efficient solutions.",
          "Proficiency and effective application of a wide range of programming languages and frameworks, including JavaScript, TypeScript, React, Python, and NodeJS.",
          "Expertise in the use of tools such as ArcGIS REST API and ArcGIS Maps SDK for JavaScript, contributing to the accuracy and effectiveness of geospatial solutions.",
          "Management and optimization of databases using PostgreSQL, ensuring data integrity and security.",
          "Proficiency in collaborative development and version control tools, such as Jira, Git, GitHub, and Bitbucket.",
        ],
        technologies: [
          "ArcGIS Maps SDK for JavaScript",
          "ArcGIS REST API",
          "Bitbucket",
          "CSS",
          "Git",
          "GitHub",
          "HTML",
          "JavaScript",
          "Jira",
          "ReactJS",
          "TypeScript",
        ],
      },
      {
        company: "SUPER MEGAVENDAS",
        role: "Full Stack Developer",
        years: "May 2024 - Jun 2024",
        location: "Cruzeiro do Sul - Acre, Brazil (Remote)",
        description: [
          "Developed and maintained SMVFlow, an internal management system, integrating payment systems and third-party tools.",
        ],
        technologies: [
          "NextJS",
          "TailwindCSS",
          "SASS",
          "TypeScript",
          "Git",
          "GitHub",
          "Jira",
          "TypeORM",
          "Figma",
          "JavaScript",
          "HTML",
          "CSS",
          "NodeJS",
          "ReactJS",
        ],
      },
      {
        company: "Innovation Serviços Digitais LTDA",
        role: "Frontend Developer",
        years: "Jun 2023 - Dec 2023",
        location: "Cruzeiro do Sul - Acre, Brazil (Remote)",
        description: [
          "Developed complete web applications using HTML, CSS, JavaScript, TypeScript, ReactJS, NextJS, and NestJS.",
          "Implemented new features, adjustments, and optimizations using Context API, Git, and Gitflow.",
          "Collaborated with multidisciplinary teams to understand requirements and deliver high-quality solutions following SCRUM.",
          "Solved complex problems using REST APIs, HTTP, JSON, and modern web technologies.",
        ],
        technologies: [
          "CSS",
          "Figma",
          "Git",
          "GitHub",
          "GitHub Actions",
          "HTML",
          "JavaScript",
          "NextJS",
          "NodeJS",
          "Prisma",
          "ReactJS",
          "SASS",
          "SQL",
          "Slack",
          "TailwindCSS",
          "TypeORM",
          "TypeScript",
        ],
      },
      {
        company: "Kenzie Academy Brasil",
        role: "Undergraduate Training Assistant",
        years: "May 2022 - Feb 2023",
        location: "Remote",
        description: [
          "Provided practical guidance on HTML, CSS, JavaScript, OOP, DOM, TypeScript, Express, NodeJS, TypeORM, Python, Django REST Framework, Flask, and SQL.",
          "Supported beginner students with questions about assessments, projects, and activities.",
          "Reviewed and corrected student assessments and module activities.",
        ],
        technologies: [
          "CSS",
          "DOM",
          "Django",
          "Express",
          "Flask",
          "Git",
          "GitHub",
          "GitHub Actions",
          "HTML",
          "JavaScript",
          "NestJS",
          "NodeJS",
          "Prisma",
          "Python",
          "SQL",
          "TypeORM",
          "TypeScript",
        ],
      },
    ],
  },
];

export const skills: ISkills = {
  programLanguages: ["JavaScript", "TypeScript", "Python", "PHP", "C#"],
  frontend: [
    "React.js",
    "Next.js",
    "Tailwind CSS",
    "Sass",
    "Vite",
    "HTML",
    "CSS",
    "shadcn/ui",
  ],
  backend: [
    "Node.js",
    "Express.js",
    "Nest.js",
    "TypeORM",
    "Prisma",
    "Django",
    "Flask",
    "FastAPI",
    "Firebase",
  ],
  database: ["PostgreSQL", "MySQL", "SQLite", "MongoDB"],
  devOps: [
    "Docker",
    "AWS",
    "GitHub Actions",
    "Google Cloud Platform",
    "Vercel",
    "Railway",
    "Linux (Ubuntu)",
    "Windows",
    "PowerShell",
  ],
  tools: [
    "Git",
    "Git Bash",
    "GitHub",
    "Bitbucket",
    "Insomnia",
    "Postman",
    "Jira",
    "Figma",
    "VS Code",
    "Notion",
    "Slack",
    "Trello",
    "Microsoft Teams",
    "Microsoft Office",
    "Gmail",
  ],
  testingAndOthers: ["Jest", "Markdown", "Regex", "NPM", "PNPM", "Yarn"],
};
